// permission -> { ROLE_CODE: scope }.  scope: 'all' | 'department' | 'self'
// Phase 0 mirrors the authorize(...) calls that exist today; later phases add entries here only.
const ALL = 'all';
const DEPT = 'department';
const ADMINS = { CEO: ALL, HR_DIRECTOR: ALL, ADMIN: ALL };

const matrix = {
  'attendance.punch': { CEO: 'self', HR_DIRECTOR: 'self', LINE_MANAGER: 'self', EMPLOYEE: 'self' },
  'attendance.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'attendance.report': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'attendance.kiosk': { KIOSK: ALL, HR_DIRECTOR: ALL, CEO: ALL },
  'attendance.adjust': { CEO: ALL, HR_DIRECTOR: ALL },
  'attendance.appeals.review': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'contract.read': { CEO: ALL, HR_DIRECTOR: ALL, EMPLOYEE: 'self' },
  'contract.manage': { CEO: ALL, HR_DIRECTOR: ALL },
  'employee.list': { CEO: ALL, HR_DIRECTOR: ALL, ADMIN: ALL, LINE_MANAGER: DEPT, EMPLOYEE: ALL },
  'employee.read': { CEO: ALL, HR_DIRECTOR: ALL, ADMIN: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'employee.create': { CEO: ALL, HR_DIRECTOR: ALL },
  'employee.import': { CEO: ALL, HR_DIRECTOR: ALL },
  'employee.offboard': { CEO: ALL, HR_DIRECTOR: ALL },
  'employee.update': { CEO: ALL, HR_DIRECTOR: ALL },
  'payroll.periods.read': { CEO: ALL, HR_DIRECTOR: ALL },
  'payroll.payslips.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: 'self', EMPLOYEE: 'self' },
  'payroll.lock': { CEO: ALL, HR_DIRECTOR: ALL },
  'payroll.transfer': { CEO: ALL, HR_DIRECTOR: ALL },
  'payroll.calculate': { CEO: ALL, HR_DIRECTOR: ALL },
  'payroll.update': { CEO: ALL, HR_DIRECTOR: ALL },
  'ot.create': { CEO: 'self', HR_DIRECTOR: 'self', LINE_MANAGER: 'self', EMPLOYEE: 'self' },
  'ot.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'ot.approve': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'ot.reject': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'claim.create': { CEO: 'self', HR_DIRECTOR: 'self', LINE_MANAGER: 'self', EMPLOYEE: 'self' },
  'claim.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'claim.approve': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'claim.reject': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'leave.create': { CEO: 'self', HR_DIRECTOR: 'self', LINE_MANAGER: 'self', EMPLOYEE: 'self' },
  'leave.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'leave.approve': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'leave.reject': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'user.read': ADMINS,
  'user.create': ADMINS,
  'user.update': ADMINS,
  'user.resetPassword': ADMINS,
  'department.manage': { CEO: ALL, HR_DIRECTOR: ALL },
  'position.manage': { CEO: ALL, HR_DIRECTOR: ALL },
  'audit.read': { CEO: ALL, ADMIN: ALL },
  'project.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'squad.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'squad.create': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'notification.read': { CEO: 'self', HR_DIRECTOR: 'self', LINE_MANAGER: 'self', EMPLOYEE: 'self', ADMIN: 'self' },
  'notification.create': { CEO: ALL, HR_DIRECTOR: ALL },
  'notice.read': { CEO: 'self', HR_DIRECTOR: 'self', LINE_MANAGER: 'self', EMPLOYEE: 'self', ADMIN: 'self' },
  'notice.manage': { CEO: ALL, HR_DIRECTOR: ALL },
  'handbook.read': { CEO: 'self', HR_DIRECTOR: 'self', LINE_MANAGER: 'self', EMPLOYEE: 'self', ADMIN: 'self' },
  'handbook.manage': { CEO: ALL, HR_DIRECTOR: ALL },
  'analytics.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'analytics.insight': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'analytics.risk': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'review.write': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'review.delete': { CEO: ALL, HR_DIRECTOR: ALL },
  'pip.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'pip.manage': { CEO: ALL, HR_DIRECTOR: ALL },
  'pip.propose': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'pip.track': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
  'dashboard.read': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT, EMPLOYEE: 'self' },
  'project.create': { CEO: ALL, HR_DIRECTOR: ALL, LINE_MANAGER: DEPT },
};

module.exports = { matrix };
